language: android
android:
  components:
    - tools
    - tools
    - platform-tools

    # BuildTools
    - build-tools-25.0.2

    # SDK version
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-25
    
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: required
    
jdk:
    - oraclejdk8 

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true

install: true
    
before_script:
    - cd ScholarsProgramApp
    - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-25
    - android list targets
    - chmod 777 gradlew
    - echo no | android create avd --force -n test -t "android-21" --abi default/armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script:
    - ./gradlew build connectedCheck
    - ./gradlew test
    
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
